HANDLER_TYPE_KEYVAULT = 'keyvault'
HANDLER_TYPE_COMMAND = 'command'
HANDLER_TYPE_FILE = 'file'
HANDLER_TYPE_VAULTWARDEN = 'vaultwarden'
HANDLERS = [
    HANDLER_TYPE_KEYVAULT,
    HANDLER_TYPE_COMMAND,
    HANDLER_TYPE_FILE,
    HANDLER_TYPE_VAULTWARDEN,
]
